### ISSUE TITLE
Segmentation faults when using vcpkg on ubuntu-24.04-arm64 runner

### ISSUE THREAD

**Issue by Evagan2018** [actions/partner-runner-images#46]
We are facing segmentation faults in GHA when vcpkg is used on a ubuntu-24.04-arm64 runner.
    i.e.
    https://github.com/Evagan2018/AVH-Hello/actions/runs/13136182081/job/36651990303
    https://github.com/Evagan2018/AVH-Hello/actions/runs/13136369731/job/36652581636
    https://github.com/Evagan2018/AVH-Hello/actions/runs/13136500059/job/36653010183
    
This is not the case when GHA runs-on: ubuntu-latest
    i.e.
    https://github.com/Evagan2018/AVH-Hello/actions/runs/13136500073

**Comment by julienbonastre** [comment]
Try again, might be working now, ours "magically" was fixed yesterday (no comment or update from GH support on our ticket though) without us changing a thing and no more seg faults on v2.233.0 ubuntu-24.04 arm64 large hosted runner too

**Comment by Evagan2018** [comment]
Good morning Julien,
Thanks a lot for you message.
Unfortunately the issue still persists. 
Even the first job of the workflow (this workflow has 60 jobs) is failing: https://github.com/Evagan2018/AVH-Hello/actions/runs/13195800802/job/36836828669
The same workflow on a x86_amd64 runner works fine: https://github.com/Evagan2018/AVH-Hello/actions/runs/13136500073
Kind regards
Eve

**Comment by jasonrandrews** [comment]
Thanks for your patience with the random failures. We discovered it was an issue with the underlying hardware and have migrated all the runners to a different arm64 sku (dpdsv5) and this should solve the errors you were seeing. We reported the issues to the Microsoft Azure team, and they are working to debug them, but in the meantime we have migrated our runners so that you can use the runners without issue.  Please create a new issue is you are still having issues with the arm64 runners.
